[package]
name = "teleprompt-render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
teleprompt-manifest = { path = "../teleprompt-manifest" }
teleprompt-core = { path = "../teleprompt-core" }
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
teleprompt-testkit = { path = "../teleprompt-testkit" }
serde_json.workspace = true
